import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1700000000000 implements MigrationInterface {
    name = 'InitialSchema1700000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "studies" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "researcher_id" character(26) NOT NULL, "title" text NOT NULL, "irb_number" text NOT NULL, "status" character varying NOT NULL DEFAULT 'pending_review', "eligibility_criteria" jsonb NOT NULL, "info_sheet_url" text NOT NULL, "target_count" integer NOT NULL, "compensation_details" text, CONSTRAINT "PK_b100ff0c4a0ad02a9c2270d45b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54723b72e60e001eb7f7540662" ON "studies" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2340346a0bfbb1f3741c3b446d" ON "studies" ("researcher_id") `);
        await queryRunner.query(`CREATE TABLE "programs" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "org_id" character(26) NOT NULL, "title" text NOT NULL, "type" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending_review', "eligibility_criteria" jsonb NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_d43c664bcaafc0e8a06dfd34e05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_57a1e919ad107914e7778a33a0" ON "programs" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d27843d20a4266a9f9285b84e" ON "programs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a1ac1fe8476545a8e08d860c3" ON "programs" ("org_id") `);
        await queryRunner.query(`CREATE TYPE "public"."patients_gender_enum" AS ENUM('male', 'female', 'other', 'prefer_not_to_say')`);
        await queryRunner.query(`CREATE TABLE "patients" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "user_id" character(26) NOT NULL, "hmo_id" character(26), "name" text NOT NULL, "phone" text, "membership_number" text, "date_of_birth" date, "gender" "public"."patients_gender_enum", "address" text, "condition_tags" text array NOT NULL DEFAULT '{}', "medication_list" jsonb, "direct_contact_shared" boolean NOT NULL DEFAULT false, "country" character varying(10), "primary_language" character varying(10), "is_caregiver" boolean NOT NULL DEFAULT false, "timezone" text, "medication_reminders_enabled" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_7fe1518dc780fd777669b5cb7a0" UNIQUE ("user_id"), CONSTRAINT "UQ_8e8e6b29f954d02d0cf410dbaff" UNIQUE ("phone"), CONSTRAINT "UQ_dabfa1cf11f8fef7d5be1b3879e" UNIQUE ("membership_number"), CONSTRAINT "PK_a7f0b9fcbb3469d5ec0b0aceaa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e8e6b29f954d02d0cf410dbaf" ON "patients" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea1f232574225b5a9d67268844" ON "patients" ("hmo_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7fe1518dc780fd777669b5cb7a" ON "patients" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."hmo_link_requests_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "hmo_link_requests" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "patient_id" character(26) NOT NULL, "org_id" character(26) NOT NULL, "status" "public"."hmo_link_requests_status_enum" NOT NULL DEFAULT 'pending', "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_c6235b701526926623a6f43f4a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c836b79a2da7be211d71174288" ON "hmo_link_requests" ("patient_id", "org_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6404f03a7f7f14f3ae112f893b" ON "hmo_link_requests" ("org_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a7d8346f8ccf660b23ea45f3fa" ON "hmo_link_requests" ("patient_id") `);
        await queryRunner.query(`CREATE TABLE "care_events" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "patient_id" character(26) NOT NULL, "type" character varying NOT NULL, "event_date" date NOT NULL, "provider_name" character varying(200), "structured" jsonb NOT NULL, "notes" text, CONSTRAINT "PK_c139722f42b8888e65f62c1ce6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb2ee66a31d6dde459c9278915" ON "care_events" ("patient_id", "event_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd3c331b2b301154a36b0e73d5" ON "care_events" ("patient_id") `);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "name" text NOT NULL, "type" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending_verification', "contact_email" text NOT NULL, "verified_at" TIMESTAMP WITH TIME ZONE, "verified_by" character(26), "registration_number" text, "contact_phone" character varying(30), "website" character varying(500), "focus_areas" text, "operating_regions" text, "head_office_country" character varying(10), "program_description" text, "licence_number" text, "coverage_region" character varying(10), "enrolled_patient_count" character varying(20), "specialty_focus" text, CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f3770f157bd77d83ab022e92fc" ON "organizations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5a8e0c18328a68facab7f01132" ON "organizations" ("type") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "user_id" character(26) NOT NULL, "type" character varying NOT NULL, "payload" jsonb NOT NULL, "read_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5323ccd23482802bd9759e88ee" ON "notifications" ("user_id", "read_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_310667f935698fcd8cb319113a" ON "notifications" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "messages" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "sender_id" character(26) NOT NULL, "recipient_id" character(26) NOT NULL, "enrollment_id" character(26), "study_enrollment_id" character(26), "body" text NOT NULL, "read_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_566c3d68184e83d4307b86f85a" ON "messages" ("recipient_id") `);
        await queryRunner.query(`CREATE TABLE "medications" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "patient_id" character(26) NOT NULL, "name" text NOT NULL, "dosage" text NOT NULL, "condition" text NOT NULL, "frequency" text NOT NULL, "schedule_times" text array NOT NULL DEFAULT '{}', "prescriber" text NOT NULL, "specialty" text NOT NULL, "pills_remaining" integer NOT NULL, "pills_total" integer NOT NULL, "refill_date" date NOT NULL, "rxnorm_code" text, "notes" text, CONSTRAINT "PK_cdee49fe7cd79db13340150d356" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3130066025b515af290c5bf190" ON "medications" ("patient_id") `);
        await queryRunner.query(`CREATE TYPE "public"."medication_dose_logs_status_enum" AS ENUM('taken', 'pending', 'later', 'skipped', 'due_now')`);
        await queryRunner.query(`CREATE TABLE "medication_dose_logs" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "medication_id" character(26) NOT NULL, "patient_id" character(26) NOT NULL, "dose_date" date NOT NULL, "scheduled_time" text NOT NULL, "status" "public"."medication_dose_logs_status_enum" NOT NULL DEFAULT 'pending', "taken_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_73c20208a99b26b86446460222b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1e893b87b5319993bd222071d4" ON "medication_dose_logs" ("medication_id", "dose_date", "scheduled_time") `);
        await queryRunner.query(`CREATE INDEX "IDX_5291c349f63d52282a94a4e779" ON "medication_dose_logs" ("medication_id", "dose_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_7631867d08b64366bb4f5e6227" ON "medication_dose_logs" ("patient_id", "dose_date") `);
        await queryRunner.query(`CREATE TABLE "study_enrollments" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "patient_id" character(26) NOT NULL, "study_id" character(26) NOT NULL, "consent_grant_id" character(26) NOT NULL, "status" character varying NOT NULL DEFAULT 'interested', "shared_data_snapshot" jsonb NOT NULL, "direct_contact_shared" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_14e0bce3c63db323e637f56933f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bb6768e6a5efcc64c21c132505" ON "study_enrollments" ("patient_id", "study_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e9c9e32c5f61314f72773208c" ON "study_enrollments" ("study_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3e211ab1725265cf4d1b89131a" ON "study_enrollments" ("patient_id") `);
        await queryRunner.query(`CREATE TABLE "enrollments" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "patient_id" character(26) NOT NULL, "program_id" character(26) NOT NULL, "consent_grant_id" character(26) NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "shared_data_snapshot" jsonb NOT NULL, "version" integer NOT NULL, CONSTRAINT "PK_7c0f752f9fb68bf6ed7367ab00f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4bc29219e8be844a9f69f04f30" ON "enrollments" ("consent_grant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_46cbd5f5fcd422a898bfdf8aab" ON "enrollments" ("program_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aeb165d5b0692be3c5871cf41c" ON "enrollments" ("patient_id") `);
        await queryRunner.query(`CREATE TABLE "consent_grants" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "patient_id" character(26) NOT NULL, "purpose" character varying NOT NULL, "data_scopes" text array NOT NULL, "status" character varying NOT NULL DEFAULT 'not_granted', "granted_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "revoked_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, CONSTRAINT "PK_f579a04c8a9da58989fb5f387b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0eca0b4fd81d17a48929022e98" ON "consent_grants" ("patient_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c979f58e1269ffb258cc1135da" ON "consent_grants" ("patient_id", "purpose") `);
        await queryRunner.query(`CREATE TYPE "public"."user_role" AS ENUM('patient', 'ngo_admin', 'hmo_coordinator', 'researcher', 'platform_admin', 'professional', 'benefactor')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "role" "public"."user_role" NOT NULL, "org_id" character(26), "email" text NOT NULL, "password_hash" text NOT NULL, "status" text NOT NULL DEFAULT 'pending', "institution_id" character(26), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users" ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a13270cd3101fd16b8000e00d" ON "users" ("org_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "audit_log" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "actor_id" character(26) NOT NULL, "action" character varying NOT NULL, "resource_id" character(26) NOT NULL, "resource_type" text NOT NULL, "metadata" jsonb, CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2ad7930a7c2af80585c8c1b770" ON "audit_log" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f961ffa39eb30a6f91a3603ff" ON "audit_log" ("resource_type", "resource_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_15a6f5aad57db494c17986ed2e" ON "audit_log" ("actor_id") `);
        await queryRunner.query(`CREATE TYPE "public"."appointments_type_enum" AS ENUM('consultation', 'follow_up', 'lab_test', 'physiotherapy', 'specialist_review')`);
        await queryRunner.query(`CREATE TYPE "public"."appointments_status_enum" AS ENUM('confirmed', 'pending', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "appointments" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "patient_id" character(26) NOT NULL, "appointment_date" date NOT NULL, "time" text NOT NULL, "duration" text NOT NULL, "provider" text NOT NULL, "specialty" text NOT NULL, "facility" text NOT NULL, "type" "public"."appointments_type_enum" NOT NULL, "status" "public"."appointments_status_enum" NOT NULL DEFAULT 'confirmed', "note" text, CONSTRAINT "PK_4a437a9a27e948726b8bb3e36ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3959a00670b72158c332ba1107" ON "appointments" ("patient_id", "appointment_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_3330f054416745deaa2cc13070" ON "appointments" ("patient_id") `);
        await queryRunner.query(`CREATE TABLE "professional_applications" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "user_id" character(26) NOT NULL, "profession" character varying NOT NULL, "license_number" text NOT NULL, "specialty" text NOT NULL, "years_of_experience" integer NOT NULL, "phone" character varying(30) NOT NULL, "bio" text NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "rejection_reason" text, "submitted_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "reviewed_at" TIMESTAMP WITH TIME ZONE, "reviewed_by" character(26), CONSTRAINT "UQ_2c2110eeb8ea38f9156a1cf59ae" UNIQUE ("user_id"), CONSTRAINT "PK_fe2a36eb841482c4da9abc0dcf3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2b1635328b937b4f01cb408060" ON "professional_applications" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2c2110eeb8ea38f9156a1cf59a" ON "professional_applications" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "benefactor_applications" ("id" character(26) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" character(26), "updated_by" character(26), "user_id" character(26) NOT NULL, "full_name" text NOT NULL, "phone" character varying(30) NOT NULL, "reason_for_support" text NOT NULL, "id_consent_given" boolean NOT NULL DEFAULT false, "status" character varying NOT NULL DEFAULT 'pending', "rejection_reason" text, "submitted_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "reviewed_at" TIMESTAMP WITH TIME ZONE, "reviewed_by" character(26), CONSTRAINT "UQ_3de1bbe195a5e75e207ef34314c" UNIQUE ("user_id"), CONSTRAINT "PK_61786ada767f3a4ae4f45c158ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cb3cec60ed576a8378dec6903" ON "benefactor_applications" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3de1bbe195a5e75e207ef34314" ON "benefactor_applications" ("user_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_3de1bbe195a5e75e207ef34314"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cb3cec60ed576a8378dec6903"`);
        await queryRunner.query(`DROP TABLE "benefactor_applications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c2110eeb8ea38f9156a1cf59a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b1635328b937b4f01cb408060"`);
        await queryRunner.query(`DROP TABLE "professional_applications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3330f054416745deaa2cc13070"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3959a00670b72158c332ba1107"`);
        await queryRunner.query(`DROP TABLE "appointments"`);
        await queryRunner.query(`DROP TYPE "public"."appointments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."appointments_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15a6f5aad57db494c17986ed2e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f961ffa39eb30a6f91a3603ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ad7930a7c2af80585c8c1b770"`);
        await queryRunner.query(`DROP TABLE "audit_log"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a13270cd3101fd16b8000e00d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace513fa30d485cfd25c11a9e4"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."user_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c979f58e1269ffb258cc1135da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0eca0b4fd81d17a48929022e98"`);
        await queryRunner.query(`DROP TABLE "consent_grants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aeb165d5b0692be3c5871cf41c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46cbd5f5fcd422a898bfdf8aab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4bc29219e8be844a9f69f04f30"`);
        await queryRunner.query(`DROP TABLE "enrollments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e211ab1725265cf4d1b89131a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e9c9e32c5f61314f72773208c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb6768e6a5efcc64c21c132505"`);
        await queryRunner.query(`DROP TABLE "study_enrollments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7631867d08b64366bb4f5e6227"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5291c349f63d52282a94a4e779"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e893b87b5319993bd222071d4"`);
        await queryRunner.query(`DROP TABLE "medication_dose_logs"`);
        await queryRunner.query(`DROP TYPE "public"."medication_dose_logs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3130066025b515af290c5bf190"`);
        await queryRunner.query(`DROP TABLE "medications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_566c3d68184e83d4307b86f85a"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_310667f935698fcd8cb319113a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5323ccd23482802bd9759e88ee"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a8e0c18328a68facab7f01132"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3770f157bd77d83ab022e92fc"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd3c331b2b301154a36b0e73d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb2ee66a31d6dde459c9278915"`);
        await queryRunner.query(`DROP TABLE "care_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7d8346f8ccf660b23ea45f3fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6404f03a7f7f14f3ae112f893b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c836b79a2da7be211d71174288"`);
        await queryRunner.query(`DROP TABLE "hmo_link_requests"`);
        await queryRunner.query(`DROP TYPE "public"."hmo_link_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7fe1518dc780fd777669b5cb7a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea1f232574225b5a9d67268844"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e8e6b29f954d02d0cf410dbaf"`);
        await queryRunner.query(`DROP TABLE "patients"`);
        await queryRunner.query(`DROP TYPE "public"."patients_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a1ac1fe8476545a8e08d860c3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d27843d20a4266a9f9285b84e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57a1e919ad107914e7778a33a0"`);
        await queryRunner.query(`DROP TABLE "programs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2340346a0bfbb1f3741c3b446d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54723b72e60e001eb7f7540662"`);
        await queryRunner.query(`DROP TABLE "studies"`);
    }

}
